# Generated by Django 3.1 on 2020-09-04 19:53

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields



class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200901_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]